CREATE DATABASE equiporocket;

USE equiporocket;


CREATE TABLE users (
idusuario VARCHAR(7) PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
apellido VARCHAR(30) NOT NULL,
password VARCHAR(60) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users(idusuario,nombre, apellido, password) VALUES ('admin23','Gerardo', 'Cordova', 'Admin123');

CREATE TABLE hoteles (
id VARCHAR(10) PRIMARY KEY,
nombre VARCHAR(30) NOT NULL,
precio INT(6) NOT NULL,
tipo VARCHAR(50) NOT NULL,
ubicacion VARCHAR(50) NOT NULL,
descripcion TEXT NOT NULL,
checkin DATE NOT NULL,
checkout DATE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hoteles_f (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
idhotel VARCHAR(10),
foto1 VARCHAR(5) NOT NULL,
foto2 VARCHAR(5) NOT NULL,
foto3 VARCHAR(5) NOT NULL,
foto4 VARCHAR(5) NOT NULL,
estrellas INT(2) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (idhotel) REFERENCES hoteles(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE reserva (
id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
titular VARCHAR(30) NOT NULL,
idhotel VARCHAR(10) NOT NULL REFERENCES hoteles(id),
correo VARCHAR(100) NOT NULL,
npersonas INT(2) NOT NULL,
tel INT(10) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);